test: process.cpp ICTCLAS50.h
	g++ -g process.cpp ./libICTCLAS50.so  -m64  -O3 -DOS_LINUX -o test  -I /usr/include/mysql -I /home/jeffzhuang/weibo/software/boost-1_56_0_b1/include/  /home/jeffzhuang/weibo/software/boost-1_56_0_b1/lib/libboost_regex.a  -I ./mysql -L /usr/lib64/mysql    -lmysqlclient 

