test : main.cpp 
	 g++ -o test  main.cpp ./lib_zjf/libICTCLAS50.so  -m64  -O3 -DOS_LINUX  ./lib_zjf/process.o  -I /usr/include/mysql -I ./lib_zjf ./lib_zjf/libboost_regex.a  -I ./lib_zjf/mysql -L /usr/lib64/mysql    -lmysqlclient
